name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to DigitalOcean Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env

      - name: Build & Push Docker image
        run: |
          docker build --build-arg NODE_ENV=production -t ${{ secrets.DOCKER_USERNAME }}/be-kzverse:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/be-kzverse:latest

      - name: Connect to remote via SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} # Your private key from GitHub Secrets

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/be-kzverse:latest
            docker stop be-kzverse || true
            
            docker rm be-kzverse || true
            docker run -d --name be-kzverse -p 1337:1337 ${{ secrets.DOCKER_USERNAME }}/be-kzverse:latest
          EOF
